"""Tracing MySQL without touching the thirty places that query it.

The catalog reads are spread over ``app/catalog/queries.py`` and its neighbours
as thirty-odd variations of::

    with mysql_connection() as conn, conn.cursor() as cur:
        cur.execute(sql, params)

Instrumenting each of those would put logging code inside every query and give
thirty chances to forget one. Instead the *connection gateway* hands out a thin
proxy while a trace is active: it delegates everything it does not care about,
and records the statement, its parameters, the tables it touched, its latency
and the rows it returned. With no trace active the gateway hands out the real
connection and this module is never entered.

Credentials cannot reach a trace through here. The connection *settings* — host,
user, password — are never read; what is recorded is the statement text and its
bound parameters, and those go through
:func:`app.observability.retrieval_log.safe.jsonable`, which redacts by key.
"""
from __future__ import annotations

import logging
import re
import time
from typing import Any, Sequence

from app.observability.retrieval_log.recorder import Call, active, mysql_call
from app.observability.retrieval_log.safe import jsonable

logger = logging.getLogger(__name__)

#: Data sources a statement reads. Backticks are optional in the corpus of
#: statements this sees, and every one of them is generated by our own code, so
#: a regex is the right amount of parsing: it names the tables for the trace and
#: is never used to decide anything.
_TABLE = re.compile(
    r"\b(?:FROM|JOIN|INTO|UPDATE)\s+`?([A-Za-z0-9_$.]+)`?", re.IGNORECASE
)

#: The leading keyword, so a trace can be filtered to reads.
_VERB = re.compile(r"^\s*(\w+)")


def tables_in(sql: str) -> list[str]:
    """Tables/data sources the statement names, in order, deduplicated."""
    out: list[str] = []
    for name in _TABLE.findall(sql or ""):
        if name.upper() in {"SELECT", "DUAL"}:
            continue
        if name not in out:
            out.append(name)
    return out


def statement_verb(sql: str) -> str:
    match = _VERB.match(sql or "")
    return match.group(1).lower() if match else "sql"


def instrument(connection: Any, *, stage: str = "catalog") -> Any:
    """``connection``, or a tracing proxy of it while a query is being traced."""
    if active() is None:
        return connection
    return _LoggedConnection(connection, stage=stage)


class _LoggedConnection:
    """A pymysql connection with a tracing ``cursor()``. Everything else — the
    ping, the rollback, the commit, the pool's own bookkeeping — is the real
    connection's, reached through ``__getattr__``, so the pool cannot tell the
    difference."""

    __slots__ = ("_connection", "_stage")

    def __init__(self, connection: Any, *, stage: str) -> None:
        self._connection = connection
        self._stage = stage

    def cursor(self, *args: Any, **kwargs: Any) -> Any:
        cursor = self._connection.cursor(*args, **kwargs)
        try:
            return _LoggedCursor(cursor, stage=self._stage)
        except Exception:  # pragma: no cover - defence in depth
            logger.debug("Could not wrap a MySQL cursor.", exc_info=True)
            return cursor

    # The pool hands the raw connection back to callers that use it as a context
    # manager; keep that working through the proxy.
    def __enter__(self) -> Any:
        return self._connection.__enter__()

    def __exit__(self, *exc: Any) -> Any:
        return self._connection.__exit__(*exc)

    def __getattr__(self, name: str) -> Any:
        return getattr(self._connection, name)


class _LoggedCursor:
    """A cursor that records each statement as one MySQL event.

    The event is created at ``execute`` and completed as rows are fetched, so a
    statement's latency is the execution and the row count is what the caller
    actually read.
    """

    __slots__ = ("_cursor", "_stage", "_call", "_rows", "_fetched")

    def __init__(self, cursor: Any, *, stage: str) -> None:
        self._cursor = cursor
        self._stage = stage
        self._call: Call | None = None
        self._rows: list[Any] = []
        self._fetched = 0

    # -- the two statements ------------------------------------------------
    def execute(self, query: Any, args: Any = None) -> Any:
        return self._run("execute", query, args)

    def executemany(self, query: Any, args: Any = None) -> Any:
        return self._run("executemany", query, args)

    def _run(self, method: str, query: Any, args: Any) -> Any:
        self._finish_previous()
        sql = query if isinstance(query, str) else str(query)
        call = mysql_call(
            statement_verb(sql),
            stage=self._stage,
            request={
                "sql": sql,
                "parameters": jsonable(args) if args else None,
                "tables": tables_in(sql),
                "statement": method,
            },
        )
        self._call = call if isinstance(call, Call) else None
        self._rows = []
        started = time.perf_counter()
        try:
            result = getattr(self._cursor, method)(query, args)
        except BaseException as exc:
            if self._call is not None:
                self._call.fail(exc)
                self._call.commit(latency_ms=(time.perf_counter() - started) * 1000.0)
                self._call = None
            raise
        if self._call is not None:
            self._call.note(rowcount=getattr(self._cursor, "rowcount", None))
            self._call.commit(latency_ms=(time.perf_counter() - started) * 1000.0)
        return result

    # -- reading the rows --------------------------------------------------
    def fetchone(self) -> Any:
        row = self._cursor.fetchone()
        if row is not None:
            self._collect([row])
        return row

    def fetchall(self) -> Any:
        rows = self._cursor.fetchall()
        self._collect(rows)
        return rows

    def fetchmany(self, size: int | None = None) -> Any:
        rows = (
            self._cursor.fetchmany() if size is None else self._cursor.fetchmany(size)
        )
        self._collect(rows)
        return rows

    def _collect(self, rows: Sequence[Any] | None) -> None:
        """Attach fetched rows to the statement's event.

        The event is already in the trace, so this fills in the rows it returned
        rather than adding a second entry: one statement, one event, however many
        fetch calls the caller makes.
        """
        if self._call is None or not rows:
            return
        try:
            self._fetched += len(rows)
            # Past the sample cap the extra rows can only move the count, so a
            # caller reading a large result set one row at a time does not pay
            # for re-rendering the same sample on every fetch.
            if len(self._rows) < self._call.max_results:
                self._rows.extend(rows)
                self._call.row_results(self._rows, total=self._fetched)
            else:
                self._call.count_only(self._fetched)
        except Exception:  # pragma: no cover - defence in depth
            logger.debug("Could not record MySQL rows.", exc_info=True)

    def _finish_previous(self) -> None:
        self._call = None
        self._rows = []
        self._fetched = 0

    # -- everything else is the real cursor's ------------------------------
    def __enter__(self) -> "_LoggedCursor":
        enter = getattr(self._cursor, "__enter__", None)
        if enter is not None:
            enter()
        return self

    def __exit__(self, *exc: Any) -> Any:
        self._finish_previous()
        exit_ = getattr(self._cursor, "__exit__", None)
        if exit_ is not None:
            return exit_(*exc)
        self._cursor.close()
        return False

    def __iter__(self) -> Any:
        return iter(self._cursor)

    def __getattr__(self, name: str) -> Any:
        return getattr(self._cursor, name)
